// Fixed public curriculum allowlist. Generated 2026-09-10; review changes before release.
window.WIFA_ANALYTICS_TOPICS = Object.freeze({
  "betriebliches_management|7-Phasen-Modell nach Streich": "betriebliches_management_a145cefcd4db",
  "betriebliches_management|Benchmarking als Vergleichsinstrument": "betriebliches_management_fcaa26b17cb0",
  "betriebliches_management|Betriebliche Planungsprozesse": "betriebliches_management_70ccb6fbf2a1",
  "betriebliches_management|Betriebliches Zielsystem & Zielbildung": "betriebliches_management_440ef758f799",
  "betriebliches_management|Betriebsstatistik, Vergleichs- und Planungsrechnung": "betriebliches_management_3a51217dc7c9",
  "betriebliches_management|Change-Konzept und Drei-Phasen-Modell": "betriebliches_management_2466806e94fb",
  "betriebliches_management|Einsatzfelder der Personalentwicklung": "betriebliches_management_44f731cab7f5",
  "betriebliches_management|Entscheidungsprozesse in der Planung": "betriebliches_management_77d0991439c7",
  "betriebliches_management|Entscheidungstechniken und Nutzwertanalyse": "betriebliches_management_f7287a8c3d8b",
  "betriebliches_management|Explizites und implizites Wissen": "betriebliches_management_d47f19f291fd",
  "betriebliches_management|Gesprächs- & Kooperationstechniken": "betriebliches_management_382f3beb5c98",
  "betriebliches_management|Grundlagen und Ziele der Personalentwicklung": "betriebliches_management_24f2b654270c",
  "betriebliches_management|Güter-, Geld- und Werteströme im Management": "betriebliches_management_acf6704458c4",
  "betriebliches_management|Hierarchieabbau, Leitungsspanne und Delegation im Wandel": "betriebliches_management_41263591e66b",
  "betriebliches_management|Individuelles und strukturelles Wissen": "betriebliches_management_f45b42bef06a",
  "betriebliches_management|Informationstechnologie: Ziele, Einsatz und Quellen": "betriebliches_management_510b1f9ef514",
  "betriebliches_management|Instrumente der Personalentwicklung": "betriebliches_management_caa4480a2fd2",
  "betriebliches_management|Interviewtechnik und Bewerbungsgespräch": "betriebliches_management_a01554352294",
  "betriebliches_management|Kommunikationsmodelle und Gesprächsgrundlagen": "betriebliches_management_1b351c352fd8",
  "betriebliches_management|Konfliktmanagement": "betriebliches_management_f6e76a382c9f",
  "betriebliches_management|Kreativitäts- & Entscheidungstechniken": "betriebliches_management_e71f7c777082",
  "betriebliches_management|Kreativitätstechniken": "betriebliches_management_1a8199653c55",
  "betriebliches_management|Lernende Organisation": "betriebliches_management_c8415aa7125e",
  "betriebliches_management|Management und betriebliches Zielsystem": "betriebliches_management_8bdf0a35e22b",
  "betriebliches_management|Managementgrundlagen": "betriebliches_management_d0b9a31d8393",
  "betriebliches_management|Managementtechniken": "betriebliches_management_5abaa9a9afed",
  "betriebliches_management|Mediation": "betriebliches_management_fb7e39c5f044",
  "betriebliches_management|Mitarbeitergespräche": "betriebliches_management_a8a5633e95e4",
  "betriebliches_management|Moderation": "betriebliches_management_b80230826571",
  "betriebliches_management|Netzwerke und Wissensaustausch": "betriebliches_management_f46d61e3f74f",
  "betriebliches_management|Organisations- und Personalentwicklung": "betriebliches_management_13b76f154b64",
  "betriebliches_management|Organisationsentwicklung & Change Management": "betriebliches_management_02b15c44fa24",
  "betriebliches_management|Personalentwicklung": "betriebliches_management_5ed9a5721a1f",
  "betriebliches_management|Planung, Strategie & Kennzahlen": "betriebliches_management_86be0cc5166f",
  "betriebliches_management|Planungsprozesse, VUCA und Veränderungsdruck": "betriebliches_management_b8bbdebeef39",
  "betriebliches_management|Problemdiagnose: Ishikawa und FMEA": "betriebliches_management_d3e2bf04a817",
  "betriebliches_management|Projektauftrag, Ziele, Stakeholder und Projektstrukturplan": "betriebliches_management_74bd8e7937dc",
  "betriebliches_management|Projektdokumentation und Projektabschluss": "betriebliches_management_dca01c2d298b",
  "betriebliches_management|Projektmanagement": "betriebliches_management_3d8f591aa910",
  "betriebliches_management|Projektmerkmale und Projektorganisation": "betriebliches_management_76575e31abfe",
  "betriebliches_management|Projektsteuerung": "betriebliches_management_52f42f743b2e",
  "betriebliches_management|ROI-System und Balanced Scorecard": "betriebliches_management_f4bb37673b90",
  "betriebliches_management|SMART, Zielhierarchie und Zielbeziehungen": "betriebliches_management_21e5a002a269",
  "betriebliches_management|Stakeholder, Anspruchsgruppen und Zielarten": "betriebliches_management_588c1597e2e2",
  "betriebliches_management|Stellenbeschreibung und Anforderungsprofil": "betriebliches_management_2b839a188e44",
  "betriebliches_management|Strategische und operative Planung": "betriebliches_management_607be4960d56",
  "betriebliches_management|Termin-, Meilenstein-, Ablauf- und Risikoplanung": "betriebliches_management_4b9674554c68",
  "betriebliches_management|Typen wissensbasierter Arbeit und Automatisierbarkeit": "betriebliches_management_4215198f385f",
  "betriebliches_management|Umsetzung und Erfolgskontrolle der Personalentwicklung": "betriebliches_management_0c63368ad7fa",
  "betriebliches_management|Verantwortung für Personalentwicklung": "betriebliches_management_793ae075f1b9",
  "betriebliches_management|Verkaufsgespräche": "betriebliches_management_7b61bb2bb785",
  "betriebliches_management|Vier Typen betrieblicher Kennzahlen": "betriebliches_management_dbde0bfe5648",
  "betriebliches_management|Vortrag und Präsentation": "betriebliches_management_b08592b4c640",
  "betriebliches_management|Wissen erfassen, speichern und verfügbar machen": "betriebliches_management_7cdba6874869",
  "betriebliches_management|Wissensmanagement & Informationstechnologie": "betriebliches_management_5fc02f6a15a5",
  "betriebliches_management|Wissensmanagement und Informationstechnologie": "betriebliches_management_d1131dbb815e",
  "betriebliches_management|Wissensmanagement und Wissenstransfer": "betriebliches_management_34d3c37260ef",
  "betriebliches_management|Wissenstreppe: von Zeichen zur Kompetenz": "betriebliches_management_045f908a1d86",
  "betriebliches_management|Zeit- & Selbstmanagement": "betriebliches_management_5d1a35f2cad1",
  "betriebliches_management|Zeit- und Selbstmanagement": "betriebliches_management_72dfbcd5c0c6",
  "betriebliches_management|Ziele der Organisationsentwicklung": "betriebliches_management_b87ffe7d055f",
  "betriebliches_management|Zielsystem als Grundlage der Planung und SWOT": "betriebliches_management_e55af335d119",
  "bwl|Aktiengesellschaft und kombinierte Rechtsformen": "bwl_ba9061a75a8e",
  "bwl|Baustellenfertigung und ortsgebundene Leistungserstellung": "bwl_43b1f635b992",
  "bwl|Betriebliche Funktionen und deren Zusammenwirken": "bwl_d857e222bda7",
  "bwl|Businessplan: Aufbau und Nutzen": "bwl_bbfb865de8df",
  "bwl|BWL-Grundbegriffe, Einzelwirtschaften und Güterarten": "bwl_e4814cedad33",
  "bwl|Controlling & Planung": "bwl_09b2398e2a65",
  "bwl|Controlling: Planung, Steuerung und Kontrolle": "bwl_63c8987ec9c2",
  "bwl|Distributionspolitik und Vertriebswege": "bwl_ff73550b76f0",
  "bwl|Einzelunternehmen und GbR/eGbR": "bwl_023c0591ff79",
  "bwl|Existenzgründung & Rechtsformen": "bwl_f4daa5a175df",
  "bwl|Existenzgründung und Unternehmensrechtsformen": "bwl_d3762e2dc60b",
  "bwl|Fertigungsarten und Organisation der Produktion": "bwl_98f2ac9e4a3d",
  "bwl|Finanzierung & Investition": "bwl_b03b0e213617",
  "bwl|Finanzierung und Investition als spiegelbildliche Finanzentscheidungen": "bwl_ab568830fae1",
  "bwl|Finanzierung, Förderung und persönliche Gründungsvoraussetzungen": "bwl_e3afae7da317",
  "bwl|Finanzierung: Kapitalbedarf und Finanzierungsformen": "bwl_c21fa23fd183",
  "bwl|GmbH und UG (haftungsbeschränkt)": "bwl_4b26deeb7e48",
  "bwl|Gründungsphasen von der Idee bis zur Festigung": "bwl_9788cf4acb1d",
  "bwl|Haftung, Geschäftsführung und Vertretung im Vergleich": "bwl_8825ad95a5ea",
  "bwl|Investition: Entscheidung und Wirtschaftlichkeit": "bwl_4c6f642e09e9",
  "bwl|Kommunikationspolitik": "bwl_7d4d6f992690",
  "bwl|Konzentrationsformen, Ziele und Wettbewerbsgrenzen": "bwl_80cbcd0407ad",
  "bwl|Kooperation, Konzentration und Verbindungsrichtungen": "bwl_85b250c8148a",
  "bwl|Kooperationsformen und Kooperationsziele": "bwl_e6b422fd8326",
  "bwl|Logistik & Supply Chain": "bwl_caec2a8399e8",
  "bwl|Logistik und Supply Chain Management": "bwl_d6e8d1e5e15f",
  "bwl|Logistikservice: Lieferzeit, Zuverlässigkeit, Flexibilität und Beschaffenheit": "bwl_133123be4f9f",
  "bwl|Marketing, Marktforschung & F&E": "bwl_a11dc8c5ca1a",
  "bwl|Marketing: Markt- und Kundenorientierung": "bwl_8cd3ccdcbb4f",
  "bwl|Marketingmanagement und Marktforschung": "bwl_ca071113b9ec",
  "bwl|Marktforschung nach Datenart und Datenherkunft": "bwl_710b5ce75667",
  "bwl|Nachhaltigkeit und digitale Transformation": "bwl_31ad0b9c1c76",
  "bwl|OHG und KG: Personengesellschaften im Handelsgewerbe": "bwl_78fd53e7c692",
  "bwl|Personalmanagement": "bwl_09dfdb67dec6",
  "bwl|Personalwirtschaft: Aufgaben und Ziele": "bwl_4ffddda7eb21",
  "bwl|Preis- und Konditionenpolitik": "bwl_0c3ce5f03414",
  "bwl|Primäre und sekundäre Funktionen sowie Produktionszielarten": "bwl_8a1c41557009",
  "bwl|Produkt- und Sortimentspolitik": "bwl_b6ae6aa1dc7e",
  "bwl|Produktion & Leistungserstellung": "bwl_b021a39e7449",
  "bwl|Produktion: Aufgaben, Ziele und Einordnung": "bwl_280bea6bad1e",
  "bwl|Produktionsfaktoren und Materialarten": "bwl_20038d301859",
  "bwl|Produktionsplanung, Fertigungstiefe und Make-or-buy": "bwl_5ec60ac73600",
  "bwl|Rechnungswesen & Kostenrechnung": "bwl_6558f2bb3ef3",
  "bwl|Rechnungswesen: Aufgaben und Adressaten": "bwl_806b4791fccc",
  "bwl|Rechtsformwahl: zentrale Entscheidungskriterien": "bwl_d21fe436de83",
  "bwl|Standortwahl als konstitutive und mehrkriterielle Entscheidung": "bwl_49ad99b639dc",
  "bwl|Strategische und operative Unternehmensplanung": "bwl_ab7b6dd836b7",
  "bwl|Teilbereiche des Rechnungswesens": "bwl_0e4bf7a490b5",
  "bwl|Unternehmensziele, Zielhierarchie und Stakeholder": "bwl_e63a0a8966f7",
  "bwl|Unternehmenszusammenschlüsse": "bwl_6ee78aeff9fa",
  "bwl|Zusammenwirken der betrieblichen Funktionen": "bwl_7987cda8cbc3",
  "bwl|Zusammenwirken, Führung, Ziele & Nachhaltigkeit": "bwl_1dbfb9a3a2d4",
  "fuehrung_zusammenarbeit|Ablauf eines professionellen Beurteilungsgesprächs": "fuehrung_zusammenarbeit_e11ffa70302c",
  "fuehrung_zusammenarbeit|Anerkennungs- und Kritikgespräche professionell führen": "fuehrung_zusammenarbeit_8cff43896214",
  "fuehrung_zusammenarbeit|Anforderungsprofil, Fähigkeitsprofil und Potenzialanalyse": "fuehrung_zusammenarbeit_985923cd251e",
  "fuehrung_zusammenarbeit|Arbeitsgruppen, Teams und Projektgruppen: Merkmale und Gütekriterien": "fuehrung_zusammenarbeit_59ff1ac41a3e",
  "fuehrung_zusammenarbeit|Arbeitsschutz, Ergonomie und Unterweisung": "fuehrung_zusammenarbeit_ee5c4c9dd322",
  "fuehrung_zusammenarbeit|Assessment Center anforderungsbezogen gestalten": "fuehrung_zusammenarbeit_4c83f71244f8",
  "fuehrung_zusammenarbeit|Aufbau, roter Faden und inhaltliche Vorbereitung": "fuehrung_zusammenarbeit_91299899cd7e",
  "fuehrung_zusammenarbeit|Ausbilder-Eignungsverordnung und ihre vier Handlungsfelder": "fuehrung_zusammenarbeit_bf451392dd56",
  "fuehrung_zusammenarbeit|Ausbildung": "fuehrung_zusammenarbeit_92f92ec25ceb",
  "fuehrung_zusammenarbeit|Ausbildungsmethoden und handlungsorientiertes Lernen": "fuehrung_zusammenarbeit_9bb62cc1e564",
  "fuehrung_zusammenarbeit|Ausbildungsplanung und individuelle Bildungsmaßnahmen": "fuehrung_zusammenarbeit_1b92509c2ea7",
  "fuehrung_zusammenarbeit|Außer- und überbetriebliche Ausbildung, Verbund und Ausbildung als Personalentwicklung": "fuehrung_zusammenarbeit_1f7d2388ed00",
  "fuehrung_zusammenarbeit|Berufsausbildung": "fuehrung_zusammenarbeit_37121c679020",
  "fuehrung_zusammenarbeit|Beteiligte und Kooperation in der Ausbildung": "fuehrung_zusammenarbeit_272efc8cf530",
  "fuehrung_zusammenarbeit|Beurteilungs- und Beobachtungsfehler vermeiden": "fuehrung_zusammenarbeit_edc19a0d32d6",
  "fuehrung_zusammenarbeit|Beurteilungskriterien und Beurteilungssysteme": "fuehrung_zusammenarbeit_cabb709ebc8b",
  "fuehrung_zusammenarbeit|Bildungscontrolling und Transfer von Personalentwicklung": "fuehrung_zusammenarbeit_4e2f8d854607",
  "fuehrung_zusammenarbeit|Direkte und indirekte Führungsinstrumente, Delegation und Motivation": "fuehrung_zusammenarbeit_ffb25a6f48eb",
  "fuehrung_zusammenarbeit|Durchführung, Umgang mit Störungen und Nachbereitung": "fuehrung_zusammenarbeit_423eee6c36ba",
  "fuehrung_zusammenarbeit|Führungsdefizite erkennen und beheben": "fuehrung_zusammenarbeit_75120e1a2a55",
  "fuehrung_zusammenarbeit|Führungsstile & -konzepte": "fuehrung_zusammenarbeit_90799de54c08",
  "fuehrung_zusammenarbeit|Führungsstile und situatives Führungsverhalten": "fuehrung_zusammenarbeit_0a32a58c81a5",
  "fuehrung_zusammenarbeit|Führungsstile, Führungsmittel & Zusammenarbeit": "fuehrung_zusammenarbeit_4c429046d771",
  "fuehrung_zusammenarbeit|Führungstechniken": "fuehrung_zusammenarbeit_ca8b9f4fed10",
  "fuehrung_zusammenarbeit|Führungstechniken: Management by Objectives, Delegation, Exception und Systems": "fuehrung_zusammenarbeit_668747c4d277",
  "fuehrung_zusammenarbeit|Grundlagen der Führung": "fuehrung_zusammenarbeit_32b33c6de45d",
  "fuehrung_zusammenarbeit|Gruppen steuern, Störungen bearbeiten und Ergebnisse nachbereiten": "fuehrung_zusammenarbeit_38c157caadfa",
  "fuehrung_zusammenarbeit|Gruppen, Teams & Projektgruppen": "fuehrung_zusammenarbeit_81d5be8b55f3",
  "fuehrung_zusammenarbeit|Gruppendynamik, Rollen und Phasen nach Tuckman": "fuehrung_zusammenarbeit_d9002977f793",
  "fuehrung_zusammenarbeit|Instrumente der Personalentwicklung: into, on, near, off und along the job": "fuehrung_zusammenarbeit_2b3fa2ddbdc1",
  "fuehrung_zusammenarbeit|Interessenorientierte Verhandlung und Rollenkonflikte": "fuehrung_zusammenarbeit_e535a41feb4d",
  "fuehrung_zusammenarbeit|Kommunikation & Gesprächsführung": "fuehrung_zusammenarbeit_1d9ad74021f9",
  "fuehrung_zusammenarbeit|Konfliktarten, Konfliktursachen und Dynamik": "fuehrung_zusammenarbeit_a9c4eb8afa7c",
  "fuehrung_zusammenarbeit|Konfliktklärung, Mediation und Eskalation nach Glasl": "fuehrung_zusammenarbeit_b06303559d0d",
  "fuehrung_zusammenarbeit|Konfliktmanagement": "fuehrung_zusammenarbeit_fd13d71ce481",
  "fuehrung_zusammenarbeit|Konfliktmanagement & Veränderungswiderstände": "fuehrung_zusammenarbeit_1d63dbfe9ee3",
  "fuehrung_zusammenarbeit|Konfliktprophylaxe und Warnsignale": "fuehrung_zusammenarbeit_f4475e141f2b",
  "fuehrung_zusammenarbeit|Kreativitätstechniken und Methoden der Ideenfindung": "fuehrung_zusammenarbeit_87abbf2abc1c",
  "fuehrung_zusammenarbeit|Leistungsfähigkeit, Menschenbild, Verantwortung und Autorität in der Führung": "fuehrung_zusammenarbeit_15b002a1769f",
  "fuehrung_zusammenarbeit|Lernschwierigkeiten erkennen, Lernberatung führen und Förderplan entwickeln": "fuehrung_zusammenarbeit_d604191126e4",
  "fuehrung_zusammenarbeit|Lernziele und Lernbereiche": "fuehrung_zusammenarbeit_0c678dcb3fdf",
  "fuehrung_zusammenarbeit|Management by Options sowie transaktionale und transformationale Führung": "fuehrung_zusammenarbeit_6b416187da80",
  "fuehrung_zusammenarbeit|Mitarbeiterbeurteilung: Ziele, Grundsätze und Anlässe": "fuehrung_zusammenarbeit_ffee476201f9",
  "fuehrung_zusammenarbeit|Mitarbeiterförderung": "fuehrung_zusammenarbeit_13a58b3a1a99",
  "fuehrung_zusammenarbeit|Mitarbeiterförderung & Personalentwicklung": "fuehrung_zusammenarbeit_b0f26544fc2f",
  "fuehrung_zusammenarbeit|Mitarbeitergespräche": "fuehrung_zusammenarbeit_1c1290656a89",
  "fuehrung_zusammenarbeit|Mitarbeitergespräche & Beurteilung": "fuehrung_zusammenarbeit_703d2d12128f",
  "fuehrung_zusammenarbeit|Moderation & Kreativitätstechniken": "fuehrung_zusammenarbeit_4ae2acc10089",
  "fuehrung_zusammenarbeit|Moderation von Projektgruppen": "fuehrung_zusammenarbeit_c4736222487f",
  "fuehrung_zusammenarbeit|Moderation: Rolle, Zielorientierung und Vorbereitung": "fuehrung_zusammenarbeit_2261b374bff2",
  "fuehrung_zusammenarbeit|Moderationszyklus, TZI und Abgrenzung zu Diskussionsleitung und Präsentation": "fuehrung_zusammenarbeit_81d08e2c3a8e",
  "fuehrung_zusammenarbeit|Motivation & Menschenbilder": "fuehrung_zusammenarbeit_b63dcdab26fe",
  "fuehrung_zusammenarbeit|Motivation, Kommunikation, Betriebsklima und Zusammenarbeit": "fuehrung_zusammenarbeit_ad8adb80892e",
  "fuehrung_zusammenarbeit|Personalbedarfsrechnung": "fuehrung_zusammenarbeit_643fa4e9f2f6",
  "fuehrung_zusammenarbeit|Personalentwicklung & Bildungscontrolling": "fuehrung_zusammenarbeit_e95b021f6db2",
  "fuehrung_zusammenarbeit|Personalentwicklung als strategischer und kontinuierlicher Prozess": "fuehrung_zusammenarbeit_89f6e337062b",
  "fuehrung_zusammenarbeit|Personalmarketing & Personalauswahl": "fuehrung_zusammenarbeit_2e5050c26bfc",
  "fuehrung_zusammenarbeit|Personalmarketing und anforderungsbezogene Personalauswahl": "fuehrung_zusammenarbeit_8267e4942535",
  "fuehrung_zusammenarbeit|Persönliche, fachliche und pädagogische Eignung von Ausbildern": "fuehrung_zusammenarbeit_c8246e88d3bf",
  "fuehrung_zusammenarbeit|Persönlichkeit, berufliche Entwicklung und Kompetenzbereiche": "fuehrung_zusammenarbeit_a5b1ec1280cc",
  "fuehrung_zusammenarbeit|Persönlichkeit, Sozialverhalten & Vielfalt": "fuehrung_zusammenarbeit_fbdc77f56a98",
  "fuehrung_zusammenarbeit|Präsentationstechniken": "fuehrung_zusammenarbeit_c01a0da01f07",
  "fuehrung_zusammenarbeit|Projektabschluss, Übergabe und Lessons Learned": "fuehrung_zusammenarbeit_9b2c31b4d1b4",
  "fuehrung_zusammenarbeit|Projektgruppen sinnvoll besetzen und organisieren": "fuehrung_zusammenarbeit_a0153b74a7fb",
  "fuehrung_zusammenarbeit|Projekthierarchie, Projektstatus und Projektabschlussprozess": "fuehrung_zusammenarbeit_9f877b6400c0",
  "fuehrung_zusammenarbeit|Prüfungen, Ausbildungsabschluss und Wiederholung": "fuehrung_zusammenarbeit_0b13313ee4c7",
  "fuehrung_zusammenarbeit|Quantitative Personalbedarfsrechnung mit Leistungskennzahlen und Zeitzuschlägen": "fuehrung_zusammenarbeit_2bef7ae179e3",
  "fuehrung_zusammenarbeit|Rechtliche Rahmenbedingungen der Berufsausbildung": "fuehrung_zusammenarbeit_564575630f14",
  "fuehrung_zusammenarbeit|Sozialisation und Entwicklung des Sozialverhaltens": "fuehrung_zusammenarbeit_1417583a5375",
  "fuehrung_zusammenarbeit|Stärken-Schwächen-Profil, Entwicklungsplan und Erfolgskontrolle": "fuehrung_zusammenarbeit_f73d3d11c671",
  "fuehrung_zusammenarbeit|Teambesprechungen effizient vorbereiten, durchführen und nachbereiten": "fuehrung_zusammenarbeit_b64d148a244f",
  "fuehrung_zusammenarbeit|Transaktionsanalyse als Modell der Führungskommunikation": "fuehrung_zusammenarbeit_4ce4f54af0cb",
  "fuehrung_zusammenarbeit|Vielfalt, Personengruppen und Gleichbehandlung": "fuehrung_zusammenarbeit_28c6c3eeab6d",
  "fuehrung_zusammenarbeit|Visualisierung, Medienwahl und organisatorische Vorbereitung": "fuehrung_zusammenarbeit_39c0bc3b57eb",
  "fuehrung_zusammenarbeit|Widerstand gegen Veränderungen verstehen und überwinden": "fuehrung_zusammenarbeit_4225a1d49671",
  "fuehrung_zusammenarbeit|Wiedereinstiegs-, Delegations- und Bewerbungsgespräche": "fuehrung_zusammenarbeit_48e9eb20f30f",
  "fuehrung_zusammenarbeit|Ziel, Gegenstand und Erfolg einer Präsentation": "fuehrung_zusammenarbeit_ae46ad4e4284",
  "fuehrung_zusammenarbeit|Zielgruppenanalyse, Sprache, Rhetorik und Auftreten": "fuehrung_zusammenarbeit_63f67d6c085e",
  "fuehrung_zusammenarbeit|Zielorientierte Führung & Führungskonzepte": "fuehrung_zusammenarbeit_880e8d8a6f92",
  "fuehrung_zusammenarbeit|Zielorientiertes Führen, Zielsysteme und SMART": "fuehrung_zusammenarbeit_6fd6c7faa700",
  "fuehrung_zusammenarbeit|Zusammenarbeit, Kommunikation und Kooperation": "fuehrung_zusammenarbeit_7747e18b38a2",
  "investition_finanzierung|Annuitätenmethode": "investition_finanzierung_0a1e7803634a",
  "investition_finanzierung|Beteiligungs- & Mezzanine-Finanzierung": "investition_finanzierung_b945e21476a0",
  "investition_finanzierung|Beteiligungsfinanzierung": "investition_finanzierung_c26ab9b33449",
  "investition_finanzierung|Bonität und Rating": "investition_finanzierung_b7052eac999c",
  "investition_finanzierung|Dynamische Differenzinvestition und Differenzkapitalwert": "investition_finanzierung_5456e0fac550",
  "investition_finanzierung|Dynamische Investitionsrechnung & Nutzungsdauer": "investition_finanzierung_b9b7649bbc69",
  "investition_finanzierung|Dynamischer Liquiditätsplan": "investition_finanzierung_62dccdb70f5b",
  "investition_finanzierung|Factoring": "investition_finanzierung_c99f2ccb7945",
  "investition_finanzierung|Finanzierung aus Abschreibungsgegenwerten": "investition_finanzierung_be43e4dbc6f3",
  "investition_finanzierung|Finanzierung aus Rückstellungen und Kapitalfreisetzung": "investition_finanzierung_c5ed02d97c02",
  "investition_finanzierung|Finanzierungsarten": "investition_finanzierung_70287a318fc5",
  "investition_finanzierung|Finanzierungsarten nach Herkunft und Rechtsstellung": "investition_finanzierung_8c56f57374bc",
  "investition_finanzierung|Finanzierungsplanung und Kapitalstruktur": "investition_finanzierung_3e2339c380ba",
  "investition_finanzierung|Finanzierungsregeln und Anlagendeckung": "investition_finanzierung_6723b5092f90",
  "investition_finanzierung|Finanzplanung": "investition_finanzierung_ea0e9fb500b3",
  "investition_finanzierung|Gewinnvergleichsrechnung": "investition_finanzierung_5c17466d3422",
  "investition_finanzierung|Innenfinanzierung & Kapitalfreisetzung": "investition_finanzierung_7d88a2261cf1",
  "investition_finanzierung|Investitionsarten und Investitionsziele": "investition_finanzierung_7a8070868416",
  "investition_finanzierung|Investitionsentscheidung und Nutzwertanalyse": "investition_finanzierung_f3181f274eef",
  "investition_finanzierung|Investitionsgrundlagen & -entscheidungen": "investition_finanzierung_30802c392bb1",
  "investition_finanzierung|Investitionsplan und Kapitalbedarf": "investition_finanzierung_7e99ecff3470",
  "investition_finanzierung|Investitionsplanung und Investitionsrechnung": "investition_finanzierung_2649f284ad2e",
  "investition_finanzierung|Kalkulationszinsfuß und Kapitalwertmethode": "investition_finanzierung_49850fab6d86",
  "investition_finanzierung|Kapitalbedarfs-, Finanz- & Liquiditätsplanung": "investition_finanzierung_c24e337b7775",
  "investition_finanzierung|Kapitalbedarfsplanung und Working Capital": "investition_finanzierung_c2b08f421bdb",
  "investition_finanzierung|Kapitalstruktur, Finanzierungsregeln & Leverage": "investition_finanzierung_ce75e38c6b51",
  "investition_finanzierung|Kostenvergleichsrechnung": "investition_finanzierung_5932bb736cad",
  "investition_finanzierung|Kreditsicherheiten": "investition_finanzierung_b29dbcc9f46c",
  "investition_finanzierung|Kurz- & langfristige Kreditfinanzierung": "investition_finanzierung_d56ed40c7da0",
  "investition_finanzierung|Kurzfristige Kredite und Lieferantenkredit": "investition_finanzierung_bd3fe7b2e9af",
  "investition_finanzierung|Langfristige Kredite und Darlehensformen": "investition_finanzierung_30aaecd001fc",
  "investition_finanzierung|Leasing, Franchising, Finetrading und ABS": "investition_finanzierung_48daad5c6d5b",
  "investition_finanzierung|Leverage-Effekt": "investition_finanzierung_daa4213ef9fa",
  "investition_finanzierung|Liquidität und statische Liquiditätskennzahlen": "investition_finanzierung_b1bfe9b16d74",
  "investition_finanzierung|Methode des internen Zinsfußes": "investition_finanzierung_7524e105ebda",
  "investition_finanzierung|Mezzanine-Kapital": "investition_finanzierung_b5ab93e0dfd6",
  "investition_finanzierung|Rentabilitätsvergleichsrechnung": "investition_finanzierung_d14b72abe0ae",
  "investition_finanzierung|Selbstfinanzierung und Cashflow": "investition_finanzierung_05c39e94c84e",
  "investition_finanzierung|Sonderformen, Bonität & Rating": "investition_finanzierung_57011e33cbbd",
  "investition_finanzierung|Statische Amortisationsrechnung": "investition_finanzierung_e7029350ef0d",
  "investition_finanzierung|Statische Investitionsrechnung": "investition_finanzierung_fec12a502164",
  "investition_finanzierung|Statische und dynamische Investitionsrechenverfahren": "investition_finanzierung_050901262a66",
  "investition_finanzierung|Vollständige Kapitalbedarfsplanung: Gründungsaufwand und Liquiditätsreserve": "investition_finanzierung_88657dbc241a",
  "investition_finanzierung|Wirtschaftliche Nutzungsdauer": "investition_finanzierung_86534b551e64",
  "investition_finanzierung|Zeitwert des Geldes: Auf- und Abzinsung": "investition_finanzierung_5e7da02af5fa",
  "investition_finanzierung|Zusammenhang von Investition und Finanzierung": "investition_finanzierung_2fb60e67cbde",
  "logistik|ABC-Analyse": "logistik_9d19a744d4af",
  "logistik|Abfallhierarchie und betriebliche Abfallwirtschaft": "logistik_c2c867955726",
  "logistik|Ablauf des Beschaffungsprozesses": "logistik_4dcfefd7094c",
  "logistik|Analysetechniken & Beschaffungsstrategien": "logistik_1bc03f487cbf",
  "logistik|Bedarfsermittlung, Liefermengen & Lieferzeitpunkte": "logistik_ce8483adeafe",
  "logistik|Bedarfsrechnung: Brutto- und Nettobedarf": "logistik_d0b79e97c126",
  "logistik|Beschaffungscontrolling": "logistik_0a2d49e3eae8",
  "logistik|Beschaffungslogistik und Grundbegriffe": "logistik_49caffe08775",
  "logistik|Beschaffungsobjekt und Sortimentsgestaltung: Element-, Modular- und System Sourcing": "logistik_e3dbe23291e7",
  "logistik|Bestellzeitpunkt und Meldebestand": "logistik_81d9550fd086",
  "logistik|Eigen- oder Fremdlagerung und kritische Lagermenge": "logistik_237c7a650b89",
  "logistik|Ein- und Ausfuhr, Warenursprung, Präferenzen und Veredelung": "logistik_547d2567153d",
  "logistik|Einkauf und Beschaffung": "logistik_a9c9e364447e",
  "logistik|Einkaufs- und Verkaufsverträge": "logistik_5c92ac5a9e67",
  "logistik|Einkaufsorganisation & Beschaffungsprozess": "logistik_4aa2517a8457",
  "logistik|Entsorgungslogistik & Rationalisierung": "logistik_8d2440391034",
  "logistik|Entsorgungslogistik und Kreislaufgedanke": "logistik_214d664a4310",
  "logistik|EU-Zollunion sowie direkter und indirekter Außenhandel": "logistik_783184584b39",
  "logistik|Externe Transportsysteme, Verpackung & Distribution": "logistik_6d98c64b3c0d",
  "logistik|Externe Verkehrsträger und multimodaler Transport": "logistik_da99fa616e4e",
  "logistik|Feinkauf und Einkaufsverhandlung": "logistik_f8d36dc4d990",
  "logistik|Fertigungsprinzipien & interne Transportsysteme": "logistik_d71dffc9f5bf",
  "logistik|Gefahrgutbeförderung: Grundprinzipien und Regelwerke": "logistik_f693b7dfbdfe",
  "logistik|Innerbetriebliche Transportsysteme": "logistik_154f1865d6b5",
  "logistik|Kommissionierung": "logistik_0fd73ff0e2a3",
  "logistik|Ladungs- und Beförderungssicherung": "logistik_f218170326c6",
  "logistik|Lagerarten und Lagerorganisation im Industriebetrieb": "logistik_60cfdcef5cf9",
  "logistik|Lagerhaltung: Funktionen, Kosten und Kennzahlen": "logistik_15bd9febe94f",
  "logistik|Lieferantenmanagement": "logistik_35684031eda3",
  "logistik|Logistikgrundlagen, Wertschöpfungskette & SCM": "logistik_eea427425bbb",
  "logistik|Logistische Aufgaben entlang der Wertschöpfungskette": "logistik_4cff64581fd8",
  "logistik|Materialwirtschaft und Lagerhaltung": "logistik_e5093d63e979",
  "logistik|Materialwirtschaft, Lagerung & Kommissionierung": "logistik_9d97a862d617",
  "logistik|Muda: Verschwendung erkennen": "logistik_e0f6ae4d3593",
  "logistik|Operative Beschaffungsstrategien": "logistik_c5e59a954bd0",
  "logistik|Optimale Bestellmenge und Andler-Modell": "logistik_403bca036582",
  "logistik|Produktportfolio und globale Wertschöpfungsketten optimieren": "logistik_a9c8c2dca427",
  "logistik|Rationalisierungsmöglichkeiten": "logistik_ec8066329a2c",
  "logistik|Sourcing & Lieferantenmanagement": "logistik_3cfb3fdee451",
  "logistik|Sourcing-Konzepte": "logistik_5376db507027",
  "logistik|Spezielle Rechtsaspekte": "logistik_899ccfe6c8a9",
  "logistik|Transportnetzwerke: Modal Split, Vor-/Haupt-/Nachlauf und Hub-and-Spoke": "logistik_52a0e7f5147e",
  "logistik|Verpackung und Verpackungsfunktionen": "logistik_3fc76ba09254",
  "logistik|Verträge, Lieferbedingungen & Zollrecht": "logistik_2011316f5142",
  "logistik|Warenausgang und Distribution": "logistik_849cea48eef3",
  "logistik|Wareneingang": "logistik_78b9b6c4d3d6",
  "logistik|Werkstatt-, Insel- und Fließfertigung": "logistik_4e143293c907",
  "logistik|Wertstromanalyse und Prozessoptimierung": "logistik_e0cf338e772c",
  "logistik|XYZ-Analyse und Kombination mit ABC": "logistik_c4a96f49669c",
  "logistik|Ziele und Zielkonflikte der Beschaffung": "logistik_2090c2648ac4",
  "marketing|Absatzmittler und Multi-, Cross- und Omnichannel": "marketing_f00dfca52d83",
  "marketing|Ansoff-Matrix: vier Wachstumsstrategien": "marketing_19ebdb8f483e",
  "marketing|BCG-Portfolioanalyse": "marketing_1372d4344a67",
  "marketing|Connectivity, Customer Journey und virales Marketing": "marketing_e7dcd1a14ea9",
  "marketing|Copy Strategy, Kreation und Mediastrategie": "marketing_a1b0455281b7",
  "marketing|CRM und Kundenbindung im Marketing": "marketing_ee56dd69b1bc",
  "marketing|Direkter Absatz und E-Commerce": "marketing_fe6777f22884",
  "marketing|Distributionspolitik": "marketing_32189495ce5a",
  "marketing|Erfahrungskurve und Kostenvorteile": "marketing_20bc176a16f8",
  "marketing|Indirekter Absatz, Handel und Distributionsintensität": "marketing_fde64a6c4922",
  "marketing|Internationale Marketingstrategien": "marketing_3085528a4951",
  "marketing|Kommunikationspolitik": "marketing_6b8dd3c05e36",
  "marketing|Kommunikationspolitik und AIDA": "marketing_c54ebf84d7f5",
  "marketing|Kosten-, konkurrenz- und nachfrageorientierte Preisfindung": "marketing_31212196dafa",
  "marketing|Markenpolitik und Markenarchitektur": "marketing_e22b492daf25",
  "marketing|Marketinggrundlagen & Marketingziele": "marketing_16e8cbcb2447",
  "marketing|Marketinginstrumentarium/Marketingmix": "marketing_20124a8141d9",
  "marketing|Marketinginstrumente: 4P und 7P": "marketing_710a5f0bd764",
  "marketing|Marketingmix nach Güter- und Leistungsart": "marketing_aed81ef44a01",
  "marketing|Marketingmix nach Markt- & Leistungsart": "marketing_69592c37c0dc",
  "marketing|Marketingplan: von der Analyse zur Kontrolle": "marketing_6c58c984784d",
  "marketing|Marketingplanung": "marketing_00b32ece1405",
  "marketing|Marketingplanung & Marketingmix": "marketing_d72970ec2249",
  "marketing|Marketingprozess: vom Verkäufer- zum Käufermarkt": "marketing_171d03fcc618",
  "marketing|Marketingstrategien & strategische Analyse": "marketing_07bd63cd79bc",
  "marketing|Marketingziele: ökonomisch, psychografisch und SMART": "marketing_fbb50e0d77db",
  "marketing|Marktanalyse & Marktforschung": "marketing_4270a15a73f8",
  "marketing|Marktforschungsfunktionen, Forschungsprozess und begleitende Testverfahren": "marketing_925686196cb9",
  "marketing|Marktsegmentierung und Marktbearbeitung": "marketing_0fd8d5c70c01",
  "marketing|Marktstimulierung: Präferenz- und Preis-Mengen-Strategie": "marketing_ae265e9a3309",
  "marketing|Mediaplanung: Reichweite, Kontaktfrequenz und GRP": "marketing_adf4f4d9f45a",
  "marketing|Öffentlichkeitsarbeit und Corporate Identity": "marketing_8ed192bb26b4",
  "marketing|Online-Marketing und Crossmedia": "marketing_1d8eee9b44c0",
  "marketing|Porters Five Forces und Konkurrenzanalyse": "marketing_9153fcaaafab",
  "marketing|Positionierung und USP": "marketing_3d3c7d15e4fd",
  "marketing|Preis- & Konditionenpolitik": "marketing_cf7e1109fc0a",
  "marketing|Preisdifferenzierung und Yield-Management": "marketing_2a6f644a2a38",
  "marketing|Preisvariation und Konditionenpolitik": "marketing_11ee94446cd1",
  "marketing|Preisziele und Preisstrategien": "marketing_fca806f2611d",
  "marketing|Produkt-, Sortiments- & Servicepolitik": "marketing_75e585fe44a4",
  "marketing|Produktentwicklung und Diversifikationsformen": "marketing_02993c7a64ca",
  "marketing|Produktlebenszyklus und Adoptergruppen": "marketing_b06ee51c0a24",
  "marketing|Produktnutzen, Qualität und Design": "marketing_9122b7809152",
  "marketing|Produktvariation, -differenzierung, -innovation und -elimination": "marketing_4fc5d753c11f",
  "marketing|Servicepolitik": "marketing_9cd783a61f87",
  "marketing|Situationsanalyse, SWOT und Marktforschung": "marketing_60cf00b00de2",
  "marketing|Sortimentsbreite und Sortimentstiefe": "marketing_5f6228ce0f6e",
  "marketing|Sponsoring": "marketing_12549d87d840",
  "marketing|Verkaufsförderung: Verkäufer-, Händler- und Verbraucherpromotion": "marketing_8c4ff7743da2",
  "marketing|Verpackung als Produkt- und Kommunikationsinstrument": "marketing_fedc4758e094",
  "marketing|Werbeplanung, Medienwahl, TKP und Erfolgskontrolle": "marketing_1a9021898b63",
  "marketing|Wettbewerbsstrategien nach Porter": "marketing_affa22953c85",
  "marketing|Wettbewerbsverhalten und Markteintrittstiming": "marketing_b7b06217a1db",
  "rechnungswesen_controlling|Aufgaben des Controllings und Regelkreis": "rechnungswesen_controlling_554293896d0e",
  "rechnungswesen_controlling|Balanced Scorecard": "rechnungswesen_controlling_d2d6a824439a",
  "rechnungswesen_controlling|BCG-Portfolio-Matrix": "rechnungswesen_controlling_fb2484d3e638",
  "rechnungswesen_controlling|Benchmarking, Stärke-Schwäche- und Potenzialanalyse": "rechnungswesen_controlling_18fa6cec506d",
  "rechnungswesen_controlling|Beschäftigungsgrad, Leerkosten und Fixkostenverrechnung": "rechnungswesen_controlling_bc2e9782a545",
  "rechnungswesen_controlling|BWA als Datenbasis für die mehrstufige Deckungsbeitragsrechnung": "rechnungswesen_controlling_e6f71ff6d448",
  "rechnungswesen_controlling|Controlling": "rechnungswesen_controlling_ae90d456122b",
  "rechnungswesen_controlling|Controlling – Begriff, Zweck und Abgrenzung": "rechnungswesen_controlling_2c9ea1226901",
  "rechnungswesen_controlling|Controlling-Grundlagen, Aufgaben & Organisation": "rechnungswesen_controlling_e03cb8f84d63",
  "rechnungswesen_controlling|Deckungsbeitragsrechnung, Preisuntergrenzen & Break-even": "rechnungswesen_controlling_1ace86eaff8d",
  "rechnungswesen_controlling|Deckungsbeitragsrechnung: Grundlagen und Break-even": "rechnungswesen_controlling_62de016db43b",
  "rechnungswesen_controlling|Eigenfertigung oder Fremdbezug – Make-or-Buy": "rechnungswesen_controlling_d2ed650ab834",
  "rechnungswesen_controlling|Engpass und relativer Deckungsbeitrag": "rechnungswesen_controlling_a636a2e756fe",
  "rechnungswesen_controlling|Flexible Plankostenrechnung und Abweichungsanalyse": "rechnungswesen_controlling_d6393c1b849a",
  "rechnungswesen_controlling|Gap-Analyse und Produktlebenszyklus": "rechnungswesen_controlling_c068772d65ce",
  "rechnungswesen_controlling|Ist- & Normalkostenrechnung": "rechnungswesen_controlling_6f472e1a28cf",
  "rechnungswesen_controlling|Kosten- und Leistungsrechnung": "rechnungswesen_controlling_c496c9bbad54",
  "rechnungswesen_controlling|Make-or-Buy, Auftragsannahme & Engpassplanung": "rechnungswesen_controlling_a010560d906b",
  "rechnungswesen_controlling|Mehrstufige Deckungsbeitragsrechnung": "rechnungswesen_controlling_01e5d2437c4b",
  "rechnungswesen_controlling|Normalkostenrechnung – starre und flexible Form": "rechnungswesen_controlling_a294dc09834b",
  "rechnungswesen_controlling|Operatives Controlling, Kennzahlen & Berichtswesen": "rechnungswesen_controlling_dca7bba77c6e",
  "rechnungswesen_controlling|Operatives Controlling: Planung, Kennzahlen, DuPont und Berichtswesen": "rechnungswesen_controlling_fb85911ae374",
  "rechnungswesen_controlling|Organisatorische Eingliederung des Controllings": "rechnungswesen_controlling_1c4f9a4412eb",
  "rechnungswesen_controlling|Plankostenrechnung & Abweichungsanalyse": "rechnungswesen_controlling_400900cb6263",
  "rechnungswesen_controlling|Plankostenrechnung und Plankostenverrechnungssatz": "rechnungswesen_controlling_4c49421bc813",
  "rechnungswesen_controlling|Preisuntergrenze und Zusatzaufträge": "rechnungswesen_controlling_0ac73906e4ab",
  "rechnungswesen_controlling|Prozesskostenrechnung": "rechnungswesen_controlling_bb08334a4b57",
  "rechnungswesen_controlling|Strategische Controllinginstrumente": "rechnungswesen_controlling_500fb70208b0",
  "rechnungswesen_controlling|Strategisches und operatives Controlling": "rechnungswesen_controlling_892032494b13",
  "rechnungswesen_controlling|SWOT-Analyse und Strategieableitung": "rechnungswesen_controlling_abfd0b7d8f95",
  "rechnungswesen_controlling|Target Costing": "rechnungswesen_controlling_07b350b7ffcf",
  "rechnungswesen_controlling|Target Costing – vom Marktpreis zu den Zielkosten": "rechnungswesen_controlling_29d0cdf198c5",
  "rechnungswesen_controlling|Voll- & Teilkostenrechnung": "rechnungswesen_controlling_40c4955f9052",
  "rechnungswesen|Abgrenzungsrechnung von Finanzbuchhaltung zur KLR": "rechnungswesen_24e513f393c4",
  "rechnungswesen|Adressaten der Finanzbuchhaltung": "rechnungswesen_1ce8b92d42d1",
  "rechnungswesen|Äquivalenzziffernkalkulation für verwandte Produkte": "rechnungswesen_359612897c29",
  "rechnungswesen|Aufbau und Logik der Bilanz": "rechnungswesen_1af4ad3de97c",
  "rechnungswesen|Aufbereitung, Adressaten und Aussage betriebswirtschaftlicher Zahlen": "rechnungswesen_55ed36915e41",
  "rechnungswesen|Aufgaben und Funktionen der Finanzbuchhaltung": "rechnungswesen_55040b0a5365",
  "rechnungswesen|Aufgaben und Ziele der Kosten- und Leistungsrechnung": "rechnungswesen_7ad6f7e791e8",
  "rechnungswesen|Ausrichtung und Zweck der Kosten- und Leistungsrechnung": "rechnungswesen_09a932d1fccd",
  "rechnungswesen|Auswertung & Rentabilitätsrechnungen": "rechnungswesen_b6a220baa4fd",
  "rechnungswesen|Auswertung der betriebswirtschaftlichen Zahlen": "rechnungswesen_545c7c401a7c",
  "rechnungswesen|Bereiche der Finanzbuchhaltung und Nebenbücher": "rechnungswesen_a02d2737c63a",
  "rechnungswesen|Bereiche der KLR: Kostenarten, Kostenstellen und Kostenträger": "rechnungswesen_4c618e1e62cf",
  "rechnungswesen|Bestandskonten, Erfolgskonten und Buchungslogik": "rechnungswesen_c5150d95c437",
  "rechnungswesen|Bilanzierungs- und Bewertungsgrundsätze": "rechnungswesen_9f6a62f166c8",
  "rechnungswesen|Buchführungspflichten nach Handels- und Steuerrecht": "rechnungswesen_b5a0f7f55997",
  "rechnungswesen|Divisionskalkulation bei Einproduktfertigung": "rechnungswesen_0f08f676cfd2",
  "rechnungswesen|Eigenkapitalrentabilität berechnen und beurteilen": "rechnungswesen_ba85f19d0b91",
  "rechnungswesen|Einstufige Deckungsbeitragsrechnung, Break-even und Entscheidungen": "rechnungswesen_07dfc670ded8",
  "rechnungswesen|Erfassung der Kosten und kalkulatorische Kosten": "rechnungswesen_4942dc7503a7",
  "rechnungswesen|Finanzbuchhaltung": "rechnungswesen_448ffc34b11e",
  "rechnungswesen|Finanzbuchhaltung & Konten": "rechnungswesen_afe07791910d",
  "rechnungswesen|Gemeinkostenzuschlagssätze ermitteln und anwenden": "rechnungswesen_e4b559c9b315",
  "rechnungswesen|Gesamtkapitalrentabilität und Leverage-Effekt": "rechnungswesen_f6b0f419ca49",
  "rechnungswesen|Gewinn-und-Verlust-Rechnung und Jahresergebnis": "rechnungswesen_862ccb81e595",
  "rechnungswesen|GoB, Buchführungspflicht & Bewertung": "rechnungswesen_09bd27cd4ddf",
  "rechnungswesen|Grundlagen des Rechnungswesens": "rechnungswesen_7cb71ee9de14",
  "rechnungswesen|Grundlegende Aspekte des Rechnungswesens": "rechnungswesen_8bd8ffddb1ad",
  "rechnungswesen|Grundsätze ordnungsmäßiger Buchführung (GoB)": "rechnungswesen_f076d5c1fce6",
  "rechnungswesen|Handelskalkulation vom Einkauf bis zum Verkauf": "rechnungswesen_18d0af27a335",
  "rechnungswesen|Inhalte, Teilpläne und Planungsverfahren": "rechnungswesen_03916ed9fb4c",
  "rechnungswesen|Inventur, Bilanz & Jahresabschluss": "rechnungswesen_42f82d25c3f6",
  "rechnungswesen|Jahresabschluss: Zweck, Bestandteile und Aussage": "rechnungswesen_53447865ac55",
  "rechnungswesen|KLR: Grundlagen, Abgrenzung & Kostenarten": "rechnungswesen_cffb30681c35",
  "rechnungswesen|KLR: Handelskalkulation & Deckungsbeitrag": "rechnungswesen_8ce691823473",
  "rechnungswesen|KLR: Kostenstellenrechnung & BAB": "rechnungswesen_027ede6811e2",
  "rechnungswesen|KLR: Kostenträgerrechnung & Kalkulation": "rechnungswesen_d041d9d5c809",
  "rechnungswesen|KLR: Teilkostenrechnung & Break-even": "rechnungswesen_9ed96517756f",
  "rechnungswesen|Kosten gliedern: fix, variabel, Einzel- und Gemeinkosten": "rechnungswesen_8311e88a053f",
  "rechnungswesen|Kosten- und Leistungsrechnung": "rechnungswesen_2b2139b8bdfb",
  "rechnungswesen|Kostenstellenrechnung, BAB und innerbetriebliche Leistungsverrechnung": "rechnungswesen_7c64880c9495",
  "rechnungswesen|Kostenträgerzeitrechnung und Betriebsergebnis": "rechnungswesen_22787d9373c2",
  "rechnungswesen|Maschinenstundensatz und maschinenabhängige Gemeinkosten": "rechnungswesen_dd163726b59b",
  "rechnungswesen|Planungsrechnung": "rechnungswesen_757ffda4f92f",
  "rechnungswesen|Rohertrag, Handelskennzahlen und Preisobergrenze im Einkauf": "rechnungswesen_87f46cacc66b",
  "rechnungswesen|Teilbereiche des Rechnungswesens und ihre Aufgaben": "rechnungswesen_5deb9fb10b64",
  "rechnungswesen|Teilkostenrechnung, Deckungsbeitrag & Break-even": "rechnungswesen_eb2d9739fc23",
  "rechnungswesen|Umsatzrentabilität und Ergebnisbeurteilung": "rechnungswesen_ec877c09790b",
  "rechnungswesen|Vollkosten- und Teilkostenrechnung im Vergleich": "rechnungswesen_778acfe12ab3",
  "rechnungswesen|Warum Teilkostenrechnung? Beschäftigungsänderungen und relevante Kosten": "rechnungswesen_6e30495a18fa",
  "rechnungswesen|Zeit-, Betriebs- und Strukturvergleiche sowie zentrale Kennzahlen": "rechnungswesen_55c167fea1ab",
  "rechnungswesen|Zeitliche Ausgestaltung, Budgetierung und Regelkreis von Planung und Kontrolle": "rechnungswesen_4b20bd723162",
  "rechnungswesen|Zuschlagskalkulation vom Material bis zum Verkaufspreis": "rechnungswesen_ad8e097b4779",
  "recht|Ablauf und Wirkungen des Insolvenzverfahrens": "recht_f431bc6a3d3e",
  "recht|Abtretung, Factoring, Schuldübernahme, Schuldbeitritt und Aufrechnung": "recht_752bd08859ae",
  "recht|Anspruchsprüfung und Gutachtenstil": "recht_330d51567b0e",
  "recht|Arbeitsrecht": "recht_53cbfd6f45c0",
  "recht|Arbeitsschutz, Arbeitszeit, Urlaub und besonderer Schutz": "recht_b969632376b4",
  "recht|Arbeitsvertrag, Arbeitnehmerbegriff, Nachweis und Befristung": "recht_3c69fb9eb51d",
  "recht|Arbeitsvertrag, Entgelt & Kündigung": "recht_6e2488de1970",
  "recht|Beendigung, Kündigung und Kündigungsschutz": "recht_85fe3deb6fad",
  "recht|Besitz, Eigentum und Eigentumsübertragung": "recht_b7959091f41e",
  "recht|Besondere Kaufkonstellationen": "recht_19c13eebe197",
  "recht|Betriebsrat und Beteiligungsrechte": "recht_65822aefd59c",
  "recht|Betriebsverfassungs-, Tarif- & Arbeitsschutzrecht": "recht_7f29f1b8bf4b",
  "recht|BGB Allgemeiner Teil": "recht_e4685f08a2e6",
  "recht|BGB Sachenrecht": "recht_94b0c396e717",
  "recht|BGB Schuldrecht": "recht_890085abb847",
  "recht|Bürgschaft und Pfandrecht": "recht_f5f0af2f5693",
  "recht|Darlehen und Verbraucherdarlehen": "recht_33d132d78429",
  "recht|Dienstvertrag und Arbeitsvertrag": "recht_43683442441f",
  "recht|Entgelt ohne Arbeitsleistung, Krankheit und Urlaub": "recht_51483405243d",
  "recht|Fernabsatz und elektronischer Geschäftsverkehr": "recht_39580b50e69f",
  "recht|Form, Nichtigkeit und Anfechtung": "recht_b558a19cca9d",
  "recht|Garantie und Gewährleistung unterscheiden": "recht_a6c4ccce9186",
  "recht|Gerichtsstand, sachliche Zuständigkeit und Gerichtsbarkeiten": "recht_4a3097138ede",
  "recht|Gewährleistung: Kenntnis, Verjährung und Verbraucherschutz": "recht_ef7dab38a6cc",
  "recht|Gewährleistungsrechte und Vorrang der Nacherfüllung": "recht_b0f0a5edd411",
  "recht|Gewerbefreiheit, Anzeige, Erlaubnis und Untersagung": "recht_e19d5ef097db",
  "recht|Gewerberecht": "recht_8db907bcc483",
  "recht|Gewerberecht / Gewerbeordnung": "recht_8cd509dc9452",
  "recht|Gläubigerverzug / Annahmeverzug": "recht_265cb970797c",
  "recht|Grundpfandrechte und Eigentumsvorbehalt": "recht_fa05787fb1b5",
  "recht|Gutgläubiger Erwerb und Herausgabeanspruch": "recht_2870593ee38f",
  "recht|GWB: Kartellverbot und Missbrauch von Marktmacht": "recht_dcb8eaa1f58e",
  "recht|Handelsbräuche, Handelsklauseln, Incoterms und Franchise": "recht_3b65367f39b3",
  "recht|Handelsgeschäfte und Untersuchungs- und Rügepflicht": "recht_3466cf83aaba",
  "recht|Handelsgesetzbuch": "recht_bd289b82b649",
  "recht|Handelsrecht": "recht_5ad4d5c6a339",
  "recht|Handelsregister und Publizität": "recht_2508b9ac10c3",
  "recht|Handelsvertreter, Handelsmakler und Kommissionär": "recht_acf18c56c7e8",
  "recht|Hauptpflichten und Gefahrübergang beim Kauf": "recht_f105e91c5346",
  "recht|Insolvenzgründe, Antrag und Antragspflicht": "recht_7d86720a80e4",
  "recht|Kaufmannsbegriff und Kaufmannsarten": "recht_056f687ce777",
  "recht|Kaufrecht & Verbraucherschutz": "recht_b22b205aef71",
  "recht|Kaufvertrag, Trennungs- und Abstraktionsprinzip": "recht_11f5450acb4d",
  "recht|Kreditsicherheiten systematisch einordnen": "recht_7a3778391903",
  "recht|Leistungsort, Fälligkeit und Erfüllbarkeit": "recht_4bde080bdd65",
  "recht|Mängelrechte und Sicherungen im Werkvertrag": "recht_6386c467283d",
  "recht|Mehrere Schuldner, mehrere Gläubiger und Verträge zugunsten Dritter": "recht_29ff8a03a605",
  "recht|Mietvertrag und Pachtvertrag": "recht_0f8c502f4ea7",
  "recht|Pflichten von Arbeitnehmer und Arbeitgeber": "recht_15a40e6f5cf9",
  "recht|Produkthaftung und Produzentenverantwortung": "recht_5c2f7410a850",
  "recht|Prokura und Handlungsvollmacht": "recht_706d7af86c0f",
  "recht|Ratenkauf, verbundene Verträge und Leasing": "recht_a20424f631a6",
  "recht|Rechtliche Grundlagen & Methoden": "recht_f8c4f7b2cabf",
  "recht|Rechtsfähigkeit, Geschäftsfähigkeit und Deliktsfähigkeit": "recht_09b56ac1012d",
  "recht|Rechtssubjekte und Rechtsobjekte": "recht_34c680d85c33",
  "recht|Sachenrecht, Kreditsicherheiten & Insolvenz": "recht_808b34f9116b",
  "recht|Sachmangel, Rechtsmangel und Mangelzeitpunkt": "recht_ddec643b32ae",
  "recht|Schuldnerverzug und Verzögerungsschäden": "recht_5895f73e958c",
  "recht|Schuldrecht: Grundlagen, AGB, Verjährung, Gerichte & Produkthaftung": "recht_7756a37c16aa",
  "recht|Schuldverhältnisse, Gläubiger und Schuldner": "recht_e2e4ece0fbfa",
  "recht|Sicherungsübereignung und Sicherungsabtretung": "recht_1242d23714cf",
  "recht|Stellvertretung, Vollmacht und Rechtsschein": "recht_e99ee2edd426",
  "recht|Tarifvertrag, Tarifbindung, Günstigkeitsprinzip und Nachwirkung": "recht_01df7cce7ddc",
  "recht|Unerlaubte Handlung und Zurechnung fremden Verschuldens": "recht_c33e4cbdd1bd",
  "recht|Unmöglichkeit, Rücktritt und Schadensersatz": "recht_4fd4b9d186ed",
  "recht|UWG: unlautere Handlungen, Werbung und Ansprüche": "recht_535d483dbdde",
  "recht|Verjährung von Ansprüchen": "recht_db14d2ce9b5e",
  "recht|Vertragsfreiheit und ihre Grenzen": "recht_e1e7465d48de",
  "recht|Vertragsschluss, Angebot, Annahme und AGB": "recht_9337a9bfe73a",
  "recht|Weitere Vertragstypen, E-Commerce & Leistungsstörungen": "recht_897c9afd1731",
  "recht|Werkvertrag, Erfolg und Abnahme": "recht_6b36d50a700e",
  "recht|Wettbewerbsrecht": "recht_a701cbcf625f",
  "recht|Willenserklärung und Rechtsgeschäft": "recht_ea0d87c541b0",
  "steuern|Abgabenordnung": "steuern_e3fb5524ec94",
  "steuern|Abgabenordnung & Besteuerungsverfahren": "steuern_cfb842bc32a7",
  "steuern|Aufbau der AO und Merkmale eines Steuerverwaltungsakts": "steuern_90f93eadfc17",
  "steuern|Bemessungsgrundlage, Steuersätze und Entstehung der Umsatzsteuer": "steuern_728812e091cb",
  "steuern|Besteuerungsverfahren, Steuerbescheid, Bekanntgabe und Einspruch": "steuern_dd65e4705d95",
  "steuern|Bewertung und Verschonung von Betriebsvermögen": "steuern_551d28a9e17c",
  "steuern|Einkommensteuer – Abzüge, Tarif & Veranlagung": "steuern_86ab4b11a12d",
  "steuern|Einkommensteuer – Einkommensberechnung & Tarif": "steuern_9e0d1c92cbe4",
  "steuern|Einkommensteuer – Einkunftsarten & Gewinnermittlung": "steuern_815c1ea17ab7",
  "steuern|Einkommensteuer: persönliche Steuerpflicht": "steuern_7fbc1de8d229",
  "steuern|Erbschaft- & Schenkungsteuer": "steuern_77ba6bec4cbd",
  "steuern|Erbschaft- und Schenkungsteuer: Steuerpflicht, Erwerbe und Befreiungen": "steuern_64f84f0f88d2",
  "steuern|Erhebung der Einkommensteuer": "steuern_8c0ab49dfe7e",
  "steuern|Erhebung, Vollstreckung, Fristen und Folgen von Fristversäumnissen": "steuern_7252195982b3",
  "steuern|Erweiterte Steuerklassifikation und Sonderabgaben": "steuern_e21e129e646f",
  "steuern|EU-Handel, innergemeinschaftlicher Erwerb und Ausfuhr": "steuern_fda627a95e99",
  "steuern|Gewerbebetrieb, Mitunternehmerschaft und Sondervergütungen": "steuern_a5ad9e90ca83",
  "steuern|Gewerbeertrag: Hinzurechnungen, Kürzungen und Verluste": "steuern_afc3b31e8c5b",
  "steuern|Gewerbesteuer": "steuern_334fcc3642b2",
  "steuern|Gewerbesteuer: Steuergegenstand, Befreiungen und Steuerschuldner": "steuern_486389f2987d",
  "steuern|Grundbegriffe des Steuerrechts": "steuern_09718eaba2ad",
  "steuern|Grunderwerb- & Grundsteuer": "steuern_3d4e6c7d3ade",
  "steuern|Grunderwerbsteuer: Erwerbsvorgänge, Befreiungen und Gegenleistung": "steuern_1920eeb0ad82",
  "steuern|Grunderwerbsteuer: Verfahren, Steuersatz und Steuerschuldner": "steuern_bdd78b5cf16b",
  "steuern|Grundsteuer seit 2025: Grundsteuerwert statt altem Einheitswertsystem": "steuern_583b3704cb23",
  "steuern|Grundsteuerverfahren, Hebesatz, Schuldner und Fälligkeit": "steuern_a82483d42415",
  "steuern|Kapitalertragsteuer und Besteuerung von Dividenden": "steuern_79d4afac609f",
  "steuern|Körperschaftsteuer & Kapitalertragsteuer": "steuern_edc950492661",
  "steuern|Körperschaftsteuer: Steuerpflicht und Steuergegenstand": "steuern_5e3619dee73c",
  "steuern|Körperschaftsteuerliches Einkommen, nicht abziehbare Aufwendungen und Dividenden": "steuern_de372bc27b5c",
  "steuern|Körperschaftsteuersatz, Veranlagung und Zahlung": "steuern_1846792e6761",
  "steuern|Leistungsfähigkeits-, Netto- und Jahressteuerprinzip der Einkommensteuer": "steuern_07f1a11e9eac",
  "steuern|Lieferung, sonstige Leistung und Leistungsort": "steuern_98ec721d0f5d",
  "steuern|Mitunternehmerschaft & Personengesellschaften": "steuern_42ac531a6301",
  "steuern|Sieben Einkunftsarten und Ermittlung der Einkünfte": "steuern_790737a6345e",
  "steuern|Sonderausgaben, außergewöhnliche Belastungen, Verluste und Familienleistungsausgleich": "steuern_c7496988dcdf",
  "steuern|Steuerarten systematisch einteilen": "steuern_94318e28db53",
  "steuern|Steuerermäßigungen: ausländische Steuer, Parteispenden und haushaltsnahe Leistungen": "steuern_d5435da7a7e3",
  "steuern|Steuerhoheit: Gesetzgebung, Verwaltung und Ertrag": "steuern_7c8273643607",
  "steuern|Steuerklassen, Freibeträge, Steuersätze und Steuererhebung": "steuern_3c65268778bb",
  "steuern|Steuerliche Buchführungspflichten nach §§ 140 und 141 AO": "steuern_b623be0e05c6",
  "steuern|Steuerliche Grundbegriffe vom Steuergegenstand bis zum Bescheid": "steuern_1bdb8526b3a3",
  "steuern|Steuerliche Grundlagen & Systematik": "steuern_11ebdd02c622",
  "steuern|Steuermessbetrag, Freibetrag, Hebesatz und § 35 EStG": "steuern_356d27f03c47",
  "steuern|Steuerrecht in der Rechtsordnung und Rechtsquellen": "steuern_f6f9be47caf8",
  "steuern|Steuerschuldner und Reverse-Charge-Verfahren": "steuern_03c723a2fd60",
  "steuern|Umsatzsteuer – EU, Drittland & Sonderfälle": "steuern_75ff500d4bd8",
  "steuern|Umsatzsteuer – Grundlagen & Vorsteuer": "steuern_15cf8a4afaaa",
  "steuern|Umsatzsteuer-Voranmeldung, Jahreserklärung und Kleinunternehmerregelung": "steuern_5ebbdddd4faa",
  "steuern|Umsatzsteuer: System und steuerbare Umsätze": "steuern_72bae1308aba",
  "steuern|Umsatzsteuerbefreiungen und Option zur Steuerpflicht": "steuern_4df785a40c06",
  "steuern|Unternehmensbezogene Steuern": "steuern_5250e8f0bc7e",
  "steuern|Veranlagung, Grundtarif und Splittingtarif": "steuern_7c59eca008a4",
  "steuern|Verdeckte Einlage und außerbilanzielle Korrekturen bei Kapitalgesellschaften": "steuern_b09fae796b72",
  "steuern|Vom Gesamtbetrag der Einkünfte zum zu versteuernden Einkommen": "steuern_655ef60e0d9c",
  "steuern|Vorsteuerabzug: Voraussetzungen und Ausschlüsse": "steuern_b40791c13d44",
  "steuern|Wesen der Steuer und Abgrenzung zu Gebühren und Beiträgen": "steuern_7229f3b21527",
  "steuern|Zweistufige Gewinnermittlung bei Mitunternehmerschaften": "steuern_9aafe3331475",
  "unternehmensfuehrung|Ablauforganisation und Prozessgestaltung": "unternehmensfuehrung_5c3cf59de6fe",
  "unternehmensfuehrung|Analysemethoden & Betriebsstatistik": "unternehmensfuehrung_6ef7fb23cbf2",
  "unternehmensfuehrung|Arbeitszeit & Arbeitsplatz": "unternehmensfuehrung_9d9f7784a392",
  "unternehmensfuehrung|Arbeitszeit- und Arbeitsplatzgestaltung": "unternehmensfuehrung_810b63b27d5f",
  "unternehmensfuehrung|Arten der Personalentwicklung": "unternehmensfuehrung_da36c69f0bb3",
  "unternehmensfuehrung|Aufbau- & Ablauforganisation": "unternehmensfuehrung_83bbf8805b4a",
  "unternehmensfuehrung|Bestimmungsgrößen und Formen des Arbeitsentgelts": "unternehmensfuehrung_c9a90b1b8508",
  "unternehmensfuehrung|Betriebsorganisation": "unternehmensfuehrung_2a6886a09e60",
  "unternehmensfuehrung|Betriebsstatistik als Entscheidungshilfe": "unternehmensfuehrung_5a1061a09b1a",
  "unternehmensfuehrung|Bildung von Organisationseinheiten": "unternehmensfuehrung_46c64a0e2f02",
  "unternehmensfuehrung|Erweiterte Management-by-Führungstechniken": "unternehmensfuehrung_6f26958ac3c4",
  "unternehmensfuehrung|Erweiterte Organisationsprinzipien sowie funktionale und divisionale Organisation": "unternehmensfuehrung_6d4b9cc6325f",
  "unternehmensfuehrung|Führen über Motivation": "unternehmensfuehrung_53abeff1a39b",
  "unternehmensfuehrung|Führungsebenen, Zielbeziehungen und erweiterte Planungsverfahren": "unternehmensfuehrung_00f798c0a6d8",
  "unternehmensfuehrung|Führungsgrundlagen, Motivation & Führungsstile": "unternehmensfuehrung_e448edc11504",
  "unternehmensfuehrung|Führungsstile": "unternehmensfuehrung_65566f40f4da",
  "unternehmensfuehrung|Gruppenführung & Gruppenverhalten": "unternehmensfuehrung_f42c4e651335",
  "unternehmensfuehrung|Gruppenstrukturen und Gruppenverhalten": "unternehmensfuehrung_0882a921dc8b",
  "unternehmensfuehrung|Gütekriterien von Auswahl- und Beurteilungsverfahren: Wirtschaftlichkeit ergänzen": "unternehmensfuehrung_dc4fbe42638c",
  "unternehmensfuehrung|Instrumente der Aufbauorganisation": "unternehmensfuehrung_7347371e2eb7",
  "unternehmensfuehrung|Integrierte Managementsysteme": "unternehmensfuehrung_90a52486de20",
  "unternehmensfuehrung|Integrierte Managementsysteme & KVP": "unternehmensfuehrung_d84bd7e43f8f",
  "unternehmensfuehrung|Kommunikation & Konflikte": "unternehmensfuehrung_5fc12be1de9e",
  "unternehmensfuehrung|Kommunikation, aktives Zuhören und Konflikteskalation": "unternehmensfuehrung_2f018e744dad",
  "unternehmensfuehrung|Kosten- und Nutzenanalyse der Personalentwicklung": "unternehmensfuehrung_fdeac1e219bb",
  "unternehmensfuehrung|Kundenzufriedenheit messen und auswerten": "unternehmensfuehrung_8e640235b9ce",
  "unternehmensfuehrung|Leistung, Motivationstheorien und Menschenbilder": "unternehmensfuehrung_e004febf6db1",
  "unternehmensfuehrung|Leitbild, Unternehmenspolitik & Planung": "unternehmensfuehrung_55f7355fe80d",
  "unternehmensfuehrung|Management-by-Techniken": "unternehmensfuehrung_98d3bfc55fdc",
  "unternehmensfuehrung|Motivation & Führung": "unternehmensfuehrung_2678061717c5",
  "unternehmensfuehrung|Operative Planung": "unternehmensfuehrung_86fbeb004f20",
  "unternehmensfuehrung|Organisation & Organisationsformen": "unternehmensfuehrung_2d5619f4356c",
  "unternehmensfuehrung|Organisationsformen und Center-Konzepte": "unternehmensfuehrung_ac1825908ba7",
  "unternehmensfuehrung|Personalanpassung, Entgelt & Personalkosten": "unternehmensfuehrung_0593298098d0",
  "unternehmensfuehrung|Personalanpassungsmaßnahmen": "unternehmensfuehrung_997abf2cccbb",
  "unternehmensfuehrung|Personalentwicklung": "unternehmensfuehrung_d3324b8524c8",
  "unternehmensfuehrung|Personalführung und Personalplanung": "unternehmensfuehrung_cd01de0e224e",
  "unternehmensfuehrung|Personalplanung & -beschaffung": "unternehmensfuehrung_57c8530ecc65",
  "unternehmensfuehrung|Potenzialanalyse": "unternehmensfuehrung_ecad61604275",
  "unternehmensfuehrung|Potenzialanalyse & Personalcontrolling": "unternehmensfuehrung_2c5aa0664571",
  "unternehmensfuehrung|Qualitative Personalplanung und Personalbeschaffung": "unternehmensfuehrung_94d0c8683ff3",
  "unternehmensfuehrung|Qualitätsbegriffe, Qualitätskosten und Verbesserungsansätze": "unternehmensfuehrung_c06a600da8e0",
  "unternehmensfuehrung|Qualitätsmanagement": "unternehmensfuehrung_82140fe83631",
  "unternehmensfuehrung|Quantitative Personalplanung": "unternehmensfuehrung_8e6da8046860",
  "unternehmensfuehrung|Strategische Planung": "unternehmensfuehrung_1ad7b316e415",
  "unternehmensfuehrung|Unternehmensleitbild, -philosophie, -kultur und Corporate Identity": "unternehmensfuehrung_19dee8d581ca",
  "unternehmensfuehrung|Unternehmensplanung & Ziele": "unternehmensfuehrung_13a9e71d405c",
  "unternehmensfuehrung|Unternehmensziele, Führungsleitbild und Personalpolitik": "unternehmensfuehrung_48340f4741cf",
  "unternehmensfuehrung|Wertanalyse": "unternehmensfuehrung_2b0c2147e2ce",
  "unternehmensfuehrung|Zielvereinbarung und aufgabenbezogenes Führen": "unternehmensfuehrung_627d0fc02f14",
  "vertrieb|Absatzsegmentrechnung und Deckungsbeiträge": "vertrieb_1a93fe6b1468",
  "vertrieb|Absolute und relative Schutzhindernisse": "vertrieb_7b7d9b5124b5",
  "vertrieb|AGB: Einbeziehung und Inhaltskontrolle": "vertrieb_6c25b7302a2e",
  "vertrieb|Akquisitorische und physische Distribution": "vertrieb_ddfa379d33a1",
  "vertrieb|Aufgaben und Funktionen des Vertriebs": "vertrieb_2fd4306d364f",
  "vertrieb|Auslandsagenten und CIF-Grundlogik": "vertrieb_61766da9ea43",
  "vertrieb|Außenhandel & Handelspolitik": "vertrieb_ba641945a07c",
  "vertrieb|Außenhandel und europäischer Binnenmarkt": "vertrieb_f2065a58bbf9",
  "vertrieb|Benchmarking und ABC-Analyse im Vertrieb": "vertrieb_1390bd85cfce",
  "vertrieb|Direkter und indirekter Export": "vertrieb_094df638488b",
  "vertrieb|Direkter und indirekter Vertrieb": "vertrieb_031d33b9c49f",
  "vertrieb|Direktinvestition und Länderanalyse": "vertrieb_23c373d05c4a",
  "vertrieb|Direktwerbung, Telefon und elektronische Post": "vertrieb_402bc1aa50e3",
  "vertrieb|GWB: Kartellverbot und Wettbewerbsbeschränkungen": "vertrieb_7876c5b904d7",
  "vertrieb|Interkulturelle Kommunikation": "vertrieb_d036baad9014",
  "vertrieb|Interkulturelle Kompetenz": "vertrieb_086049b354e8",
  "vertrieb|Internationale Geschäftsbeziehungen & interkulturelle Kommunikation": "vertrieb_49fb7b135b56",
  "vertrieb|Internationale Institutionen und Handelsregeln": "vertrieb_6cb652b1c216",
  "vertrieb|Internationale Kooperationen & Markteintritt": "vertrieb_6368043cf3a5",
  "vertrieb|Internationale Lizenzvergabe": "vertrieb_ee7b831c8022",
  "vertrieb|Internationales Franchising": "vertrieb_a4140b2a5303",
  "vertrieb|Joint Venture und internationale Kooperation": "vertrieb_86083e32c1b8",
  "vertrieb|Key-Account-Management und persönliche Betreuung": "vertrieb_18e7f0328b87",
  "vertrieb|Kulturdimensionen als Analysehilfe": "vertrieb_999a6c4416cb",
  "vertrieb|Markenanmeldung, Schutzgebiet und Schutzdauer": "vertrieb_5c28d15d2f8d",
  "vertrieb|Markenrecht": "vertrieb_2d504dc27888",
  "vertrieb|Markenschutz: schutzfähige Zeichen und Entstehung": "vertrieb_a762eb102f1f",
  "vertrieb|Spezielle Rechtsaspekte": "vertrieb_17fb71311834",
  "vertrieb|Strategisches und operatives Vertriebscontrolling": "vertrieb_d1bd073bd633",
  "vertrieb|UWG: unlautere Geschäftspraktiken und Werbegrenzen": "vertrieb_6fa9eb8185ec",
  "vertrieb|Verbraucherschutz & AGB": "vertrieb_44eb72cc89f1",
  "vertrieb|Verbrauchsgüterkauf und Beweislastumkehr": "vertrieb_39ac694b2abe",
  "vertrieb|Vertriebscontrolling": "vertrieb_3d2aaa90a122",
  "vertrieb|Vertriebskennzahlen und Balanced Scorecard": "vertrieb_8cefaeb6800d",
  "vertrieb|Vertriebsmanagement": "vertrieb_42e4d777f972",
  "vertrieb|Vertriebsmanagement & Kundenbeziehungen": "vertrieb_3d33f3218ced",
  "vertrieb|Vertriebsorganisation & Key-Account-Management": "vertrieb_0f37f5bf2d58",
  "vertrieb|Vertriebsorganisation: Funktion, Gebiet, Produkt und Matrix": "vertrieb_c9e92f604d2c",
  "vertrieb|Vertriebswege, Absatzorgane & E-Commerce": "vertrieb_72bd790156e8",
  "vertrieb|Wettbewerbsrecht – UWG & GWB": "vertrieb_1850338756f9",
  "vertrieb|Widerrufsrecht im Fernabsatz und elektronische Widerrufsfunktion": "vertrieb_f9eee28ee5b2",
  "vwl|Angebot, Nachfrage und Preis-Mengen-Zusammenhang": "vwl_e1ed48412ab0",
  "vwl|Angebotsorientierte Wirtschaftspolitik": "vwl_033e5b9b4f43",
  "vwl|Arbeitsmarktpolitik: aktiv und passiv": "vwl_e41b7d8c6b6c",
  "vwl|Arten und Ursachen der Arbeitslosigkeit": "vwl_4c4fedb58c67",
  "vwl|Aufgabe der VGR und Bruttoinlandsprodukt": "vwl_3c9247e73246",
  "vwl|Außenwirtschaft": "vwl_0537f8809db7",
  "vwl|Außenwirtschaft, Freihandel & Protektionismus": "vwl_e45e5f25e10e",
  "vwl|Außenwirtschaftliches Gleichgewicht als Stabilitätsziel": "vwl_b3f9878df914",
  "vwl|Bedürfnis, Bedarf, Nachfrage und reine öffentliche Güter": "vwl_9a06cdcfdc2f",
  "vwl|BIP, BNE und Inlands-/Inländerkonzept": "vwl_5ec766b44b1a",
  "vwl|Deficit Spending, Staatsverschuldung und Schuldenbremse": "vwl_afbaf5e95226",
  "vwl|Einfacher und erweiterter Wirtschaftskreislauf": "vwl_8f0810d4440a",
  "vwl|Entstehungs-, Verwendungs- und Verteilungsrechnung": "vwl_8b873776f671",
  "vwl|EU-Binnenmarkt & Wirtschafts- und Währungsunion": "vwl_c13668aa9f1c",
  "vwl|EU-Binnenmarkt, Zollunion und vier Grundfreiheiten": "vwl_93596431f9f0",
  "vwl|EU-Fiskalregeln und reformierter Stabilitätsrahmen": "vwl_effd67e21e94",
  "vwl|Europäische Wirtschafts- und Währungsunion und Konvergenzkriterien": "vwl_8af8d7591467",
  "vwl|Expansive und restriktive Geldpolitik": "vwl_183480abdb11",
  "vwl|EZB, Eurosystem und Ziel der Geldpolitik": "vwl_5f565f322c09",
  "vwl|Finanzpolitik und automatische Stabilisatoren": "vwl_1fc8c314a81c",
  "vwl|Freihandel und Protektionismus": "vwl_ba15337586a7",
  "vwl|Früh-, Präsenz- und Spätindikatoren": "vwl_4de742ce61e2",
  "vwl|Funktionen des Wettbewerbs": "vwl_79e957f68726",
  "vwl|Geld- & Finanzpolitik": "vwl_8b42cebe7fb6",
  "vwl|Geldpolitische Instrumente und Transmission": "vwl_4ce0d7472dd6",
  "vwl|Gemeinsame Währung: Chancen, Risiken und aktueller Euroraum": "vwl_92550cfc0ae6",
  "vwl|Grundlagen, Bedürfnisse, Güter & ökonomisches Prinzip": "vwl_5d8a56f047fe",
  "vwl|Hoher Beschäftigungsstand und Arbeitslosenquote": "vwl_a108cc8cbae0",
  "vwl|Intrahandel, Außenhandelsquote und Aufbau der Zahlungsbilanz": "vwl_92f48337b699",
  "vwl|Konjunktur und Wirtschaftswachstum": "vwl_b42f066d594f",
  "vwl|Konjunktur, Stabilitätsziele, Arbeitslosigkeit & Inflation": "vwl_a6dabd6af4f4",
  "vwl|Konjunkturzyklus und Konjunkturphasen": "vwl_141b4b03f813",
  "vwl|Magisches Viereck und erweitertes Zielsystem": "vwl_676f42e058bf",
  "vwl|Markt, Preis und Wettbewerb": "vwl_475f994809c7",
  "vwl|Marktbegriff, Marktarten und Marktformen": "vwl_cb5342a50a5e",
  "vwl|Marktformen, Angebot, Nachfrage & Preisbildung": "vwl_60f3f7a18646",
  "vwl|Marktgleichgewicht und Marktungleichgewichte": "vwl_01746958e970",
  "vwl|Nachfrageorientierte Wirtschaftspolitik": "vwl_fac3bfe2c796",
  "vwl|Nominales und reales BIP sowie Grenzen der Aussagekraft": "vwl_8d209d0206ff",
  "vwl|Preisbildung bei Monopol und Oligopol": "vwl_7a1f283c8a4a",
  "vwl|Preisdifferenzierung und Marktsegmentierung": "vwl_b0f0795cff8d",
  "vwl|Preiselastizität des Angebots und Anpassungsfähigkeit der Produktion": "vwl_f72607320341",
  "vwl|Preiselastizität und Kreuzpreiselastizität": "vwl_b19db1935e92",
  "vwl|Preisstabilität, Verbraucherpreisindex und Inflation": "vwl_ae45654efccb",
  "vwl|Primärverteilung, Lohnquote und Gewinnquote": "vwl_fa38dcf2e007",
  "vwl|Sekundärverteilung und verfügbares Einkommen": "vwl_a760567e89a8",
  "vwl|Staatliche Eingriffe in die Preisbildung": "vwl_29a7ec49d40b",
  "vwl|Tarifpolitik, Löhne und gesamtwirtschaftliche Wirkungen": "vwl_1b6a836cf346",
  "vwl|Träger der Wirtschaftspolitik und Koordination nach dem Stabilitätsgesetz": "vwl_92649538b67e",
  "vwl|Umweltpolitik & nachfrage-/angebotsorientierte Politik": "vwl_bd19cdbc9669",
  "vwl|Umweltpolitik: Ziele, Prinzipien und Instrumente": "vwl_a0a1db764445",
  "vwl|Verschiebung von Angebots- und Nachfragekurven": "vwl_78e7a44dcea3",
  "vwl|VGR & Einkommensverteilung": "vwl_497aac207fad",
  "vwl|Volkswirtschaftliche Gesamtrechnung": "vwl_e06135a3da7e",
  "vwl|Volkswirtschaftliche Grundtatbestände": "vwl_2291999534e8",
  "vwl|Vollkommener und unvollkommener Markt": "vwl_df57f2266340",
  "vwl|Wachstums-, Tarif- & Arbeitsmarktpolitik": "vwl_b7b8c24f60b6",
  "vwl|Wachstumspolitik und Standortbedingungen": "vwl_84ed330296a0",
  "vwl|Wettbewerbspolitik & staatliche Markteingriffe": "vwl_7d55d9838b80",
  "vwl|Wettbewerbspolitik, Kartelle und Missbrauchskontrolle": "vwl_eddac8980d11",
  "vwl|Wirtschaftsordnung & Soziale Marktwirtschaft": "vwl_177fb3b65f47",
  "vwl|Wirtschaftspolitik & Stabilitätsziele": "vwl_5095f2f6a859",
  "vwl|Wirtschaftssystem, Wirtschaftsordnung und Soziale Marktwirtschaft": "vwl_ecaf6e8721ad",
  "vwl|Wirtschaftswachstum und Produktionspotenzial": "vwl_bcc25b232e41",
  "vwl|Zielharmonien und Zielkonflikte der Wirtschaftspolitik": "vwl_9cc416afcf99"
});
